//Skeleton File Generated by ChatGPT

export default function Loading() {
  return (
    <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
      <main className="flex flex-1 w-full max-w-3xl flex-col items-center justify-between py-32 px-16 bg-white dark:bg-black sm:items-start">
              <section className="w-full animate-pulse"> {/* makes rectangles pulse to show loading */}
          {/* Welcome heading */}
                  <div className="h-10 w-3/4 bg-gray-300 rounded mb-4"></div> {/* large rectangle */}

          {/* Introduction */}
                  <div className="h-6 w-2/3 bg-gray-300 rounded mb-8"></div> {/* smaller rectangle */}

          {/* Project 1 */}
                  <div className="mb-8"> {/* project-shaped section */}
            <div className="h-7 w-1/2 bg-gray-300 rounded mb-3"></div>
            <div className="h-4 w-full bg-gray-300 rounded mb-2"></div>
            <div className="h-4 w-3/4 bg-gray-300 rounded mb-3"></div>
            <div className="h-4 w-1/2 bg-gray-300 rounded"></div>
          </div>

                  {/* Project 2 */} {/* project shaped section */}
          <div className="mb-8">
            <div className="h-7 w-1/2 bg-gray-300 rounded mb-3"></div>
            <div className="h-4 w-full bg-gray-300 rounded mb-2"></div>
            <div className="h-4 w-3/4 bg-gray-300 rounded mb-3"></div>
            <div className="h-4 w-1/2 bg-gray-300 rounded"></div>
          </div>
        </section>
      </main>
    </div>
  );
}
